/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2020-06-03 18:28:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.Analitics;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Display_005fRecord_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/jsp/Analitics/../../resources/css/common.css", Long.valueOf(1590763151226L));
    _jspx_dependants.put("jar:file:/C:/Users/gce/.m2/repository/org/springframework/spring-webmvc/5.1.10.RELEASE/spring-webmvc-5.1.10.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1569683330000L));
    _jspx_dependants.put("file:/C:/Users/gce/.m2/repository/org/springframework/spring-webmvc/5.1.10.RELEASE/spring-webmvc-5.1.10.RELEASE.jar", Long.valueOf(1571233170982L));
    _jspx_dependants.put("jar:file:/C:/Users/gce/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153399482000L));
    _jspx_dependants.put("file:/C:/Users/gce/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1571152422633L));
    _jspx_dependants.put("/WEB-INF/jsp/Analitics/../../resources/js/reportfunctions.js", Long.valueOf(1590770459010L));
    _jspx_dependants.put("jar:file:/C:/Users/gce/.m2/repository/org/springframework/spring-webmvc/5.1.10.RELEASE/spring-webmvc-5.1.10.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1569683330000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "ModelLibrary.jsp", out, false);
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<title>Display The Record Created</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <style>");
      out.write("body {\r\n");
      out.write("    padding-bottom: 40px;\r\n");
      out.write("    background-color: #eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr {\r\n");
      out.write("  border: 0;\r\n");
      out.write("  clear:both;\r\n");
      out.write("  display:block;\r\n");
      out.write("  width: 96%;               \r\n");
      out.write("  height: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the header */\r\n");
      out.write(".headder{\r\n");
      out.write("    padding-bottom: 5px;\r\n");
      out.write("    padding-left: 20px;\r\n");
      out.write("    padding-right: 10px;\r\n");
      out.write("\tbackground-color: #CE2B1C;\t\r\n");
      out.write("\tborder-style: outset;\r\n");
      out.write("\tborder-radius: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the corporate logo */\r\n");
      out.write("p.c {\r\n");
      out.write("\tcolor: gold;\r\n");
      out.write("  \tfont-style: oblique;\r\n");
      out.write("  \tpadding-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*Standard user input format */\r\n");
      out.write(".form-signin {\r\n");
      out.write("    max-width: 330px;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin .form-signin-heading,\r\n");
      out.write(".form-signin .checkbox {\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin .checkbox {\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin .form-control {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    -webkit-box-sizing: border-box;\r\n");
      out.write("    -moz-box-sizing: border-box;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin .form-control:focus {\r\n");
      out.write("    z-index: 2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin input {\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    border-bottom-right-radius: 0;\r\n");
      out.write("    border-bottom-left-radius: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin button {\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".has-error {\r\n");
      out.write("    color: red\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*Main Page Layout format*/\r\n");
      out.write("main{\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth:950px;\r\n");
      out.write("\tpadding-top: 5px;\r\n");
      out.write("\tpadding-left: 30px;\r\n");
      out.write("\tpadding-right: 20px;\r\n");
      out.write("\t\r\n");
      out.write("\tborder-right: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("aside{\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\twidth:350px;\r\n");
      out.write("\tpadding-bottom:20px;\r\n");
      out.write("\tpadding-left: 4px;\r\n");
      out.write("\tpadding-right: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer{\r\n");
      out.write("\tclear:both;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tfont-size:.8em;\r\n");
      out.write("\tpadding-top:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#container, footer{\r\n");
      out.write("\twidth:90%;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tmargin-bottom: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("aside section {\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tborder-bottom: 1px solid black;\r\n");
      out.write("\tcolor:black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*Display Data Page*/\r\n");
      out.write("/* To make the buttons look like hyperlink words in a normal sentence I modified a button style from the CSS style guide:\r\n");
      out.write("\thttps://www.w3schools.com/howto/howto_css_text_buttons.asp*/\r\n");
      out.write(".astext {\r\n");
      out.write("    background:none;\r\n");
      out.write("    border:none;\r\n");
      out.write("    margin:0;\r\n");
      out.write("    padding:0;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".astext:hover {background: #eee;}\r\n");
      out.write("\r\n");
      out.write(".Calculate {color: dodgerblue;}\r\n");
      out.write(".Restart {color: orange;}\r\n");
      out.write("\r\n");
      out.write("fieldset { position: relative; padding: 0.35em 0.625em 0.75em; }\r\n");
      out.write(".legend2 { position: absolute; bottom: -1.4ex; left: 10px; background: white  }\r\n");
      out.write("caption, .legend2 { padding: 0 2px }\r\n");
      out.write("\r\n");
      out.write("#message{\r\n");
      out.write("\tbackground: #eee;\r\n");
      out.write("\tfont-size: 12pt;\r\n");
      out.write("}\r\n");
      out.write("#tital1{\r\n");
      out.write("\tpadding-left: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".display{\r\n");
      out.write("\tpadding-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Populate{\r\n");
      out.write("\tpadding-left: 20px\r\n");
      out.write("}\r\n");
      out.write("#intro{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: large;\r\n");
      out.write("}\r\n");
      out.write("#arrayDisply{\r\n");
      out.write("\tpadding-left: 90px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("fieldset\r\n");
      out.write("{\r\n");
      out.write("  background-color:#CCC;\r\n");
      out.write("  max-width:700px;\r\n");
      out.write("  padding:16px;\t\r\n");
      out.write("      border:2px black;\r\n");
      out.write("    -moz-border-radius:8px;\r\n");
      out.write("    -webkit-border-radius:8px;\t\r\n");
      out.write("    border-radius:8px;\t\r\n");
      out.write("}\r\n");
      out.write(".legend1\r\n");
      out.write("{\r\n");
      out.write("  margin-bottom:0px;\r\n");
      out.write("  margin-left:16px;\r\n");
      out.write("}\r\n");
      out.write(".legend2\r\n");
      out.write("{\r\n");
      out.write("\tbackground:transparent;\r\n");
      out.write("  margin-bottom:0px;\r\n");
      out.write("  margin-left:16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*Display record Page*/\r\n");
      out.write(".printResult{\r\n");
      out.write("\tpadding-top:5px;\r\n");
      out.write("\tpadding-left: 145px;\r\n");
      out.write("\tpadding-right: 145px;\r\n");
      out.write("}\r\n");
      out.write("#UserChoice1{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("#sizecontroll{\r\n");
      out.write("\tpadding-right: 400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*Display Table*/\r\n");
      out.write(".SearchStatement{\r\n");
      out.write("\tpadding-left: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#MasterTable {\r\n");
      out.write("  \t\tfont-family: arial, sans-serif;\r\n");
      out.write("  \t\tborder: 2px solid black;\r\n");
      out.write("  \t\twidth: 95%;\r\n");
      out.write("  \t\tmargin-left: 2.5%; \r\n");
      out.write("    \tmargin-right: 2.5%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("#tital2{text-align: center;}\r\n");
      out.write("#FailedResult{\r\n");
      out.write("\t\twidth: 30%;\r\n");
      out.write("  \t\tmargin-left: 35%; \r\n");
      out.write("    \tmargin-right: 35%;\r\n");
      out.write("    \ttext-align: center; \r\n");
      out.write("    \tcolor: red;\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#Searchbar{\r\n");
      out.write("\t\twidth: 30%;\r\n");
      out.write("  \t\tmargin-left: 35%; \r\n");
      out.write("    \tmargin-right: 35%; \t\r\n");
      out.write("}\r\n");
      out.write("#searcline{width: 83%;}\r\n");
      out.write("\r\n");
      out.write(".BuildTepfile{\r\n");
      out.write("\tpadding-left: 15px;\r\n");
      out.write("\tpadding-right: 280px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*Modal format*/\r\n");
      out.write(".modal-content{background: #eee;}\r\n");
      out.write(".modal-title{float: left;}\r\n");
      out.write("#SearchParamiters{float: right}\r\n");
      out.write("  textarea.window {\r\n");
      out.write("  \tbackground: #eee;\r\n");
      out.write("    display: block;\r\n");
      out.write("    border: none;\r\n");
      out.write("    margin-left: auto;\r\n");
      out.write("    margin-right: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#saveandnew{\r\n");
      out.write("\tpadding-left: 260px;\r\n");
      out.write("}\r\n");
      out.write("#spacer{\r\n");
      out.write("\tpadding-left: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*Chart format Display settings*/\r\n");
      out.write("/*To center an element vertically, I adopted a solution from the CSS style guide:\r\n");
      out.write("\thttps://www.w3.org/Style/Examples/007/center.en.html*/\r\n");
      out.write(".main-display {\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("}\r\n");
      out.write(".column {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tmargin: 10px 10px 10px 10px;\r\n");
      out.write("\twidth: 47%;\t\r\n");
      out.write("}\r\n");
      out.write(".item {\r\n");
      out.write("\twidth: 85%;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("\tmargin-right: auto;\r\n");
      out.write("\tmin-height: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the Report footer */\r\n");
      out.write("footer2{\t\r\n");
      out.write("\twidth: 98%;\r\n");
      out.write("\tbackground-color: Gray;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tborder: solid 1px black;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write(".container button{display: inline-block;}\r\n");
      out.write("#btn1{ float:left;}\r\n");
      out.write("#btn3{ float:right;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("  <script>");
      out.write("/*!\r\n");
      out.write(" * JavaScript Methods (https://github.com/Aaron-Larch/Websight-Protobuild)\r\n");
      out.write(" * Copyright 2020-2025 GCE, Inc.\r\n");
      out.write(" * Created by Aaron Larch\r\n");
      out.write(" */\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("\t// Get a modal\r\n");
      out.write("\tthis.loadModal = function(input){\r\n");
      out.write("\t\t$(\"#AssineParamiters\").modal().on('shown.bs.modal', function (e) {loadValues(\".PopUpModal\", \".CreateNewRecord\", input)});\r\n");
      out.write("\t\tload_page('/WEB-INF/ModelLibrary.jsp #container');\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tthis.getModal = function(){\r\n");
      out.write("\t\t$(\"#CreateNewRecord\").modal().on('shown.bs.modal');\r\n");
      out.write("\t\tload_page('/WEB-INF/ModelLibrary.jsp #container');\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t//function to call popup window\r\n");
      out.write("\tthis.loadPopUp =function (input){\r\n");
      out.write("\t\t$(\"#PopUpModal\").modal().on('shown.bs.modal', function (e) {loadContent(input);});\r\n");
      out.write("\t\tload_page('/WEB-INF/ModelLibrary.jsp #container');\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t//Switch states button\r\n");
      out.write("\tthis.SwichLoadout= function(a){\r\n");
      out.write("\t\tif(a==1){\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".Populate\"), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".display\"), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".Populate\"), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll('.display'), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\t//Check all function\r\n");
      out.write("\tthis.checkAll=function(source) {\r\n");
      out.write("\t\t  checkboxes = document.getElementsByName('operation');\r\n");
      out.write("\t\t  for(var i=0; i<checkboxes.length; i++) {\r\n");
      out.write("\t\t    checkboxes[i].checked = source.checked;\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\r\n");
      out.write("\tthis.renderChart();\r\n");
      out.write("})\t\r\n");
      out.write("\r\n");
      out.write("function load_page(url){$('modal-isi-body').load(url) ;}\r\n");
      out.write("\r\n");
      out.write("//Display a combination of classes based of a given variabule\r\n");
      out.write("function loadValues(class1, class2, flag){\r\n");
      out.write("\tif(flag==\"page1\"){\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(class1), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(class2), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t}else if(flag==\"page2\"){\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(class2), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(class1), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//Select a string from an array of strings based on user input \r\n");
      out.write("function loadContent(input) {\r\n");
      out.write("\tdocument.getElementById(\"Display\").value = \"\";\r\n");
      out.write("\t//convert string into an array of strings\r\n");
      out.write("\tvar JsArray = document.getElementById('DisplayValue').innerHTML;\r\n");
      out.write("\tvar block = JsArray.substring(1, JsArray.length-1);\r\n");
      out.write("\tvar string = block.split(\"break\");\r\n");
      out.write("\tif(input > 0){ //Search array\r\n");
      out.write("\t\tvar quickfix=string[input].substring(2, string[input].length);\r\n");
      out.write("\t\tdocument.getElementById('Display').value=quickfix;\r\n");
      out.write("\t}else{document.getElementById('Display').value=string[input];}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function loadChannel(cl1, cl2, cl3, cl4, flag){\r\n");
      out.write("\tif(flag==\"Step1\"){\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl1), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl2), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl3), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t}else if(flag==\"Step2\"){\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl4), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl2), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl3), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t}else if(flag==\"Step3\"){\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl4), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl1), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl2), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl4), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl1), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl3), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function buildReport(\r\n");
      out.write("\t\txAxsis,\r\n");
      out.write("\t\tbellData,\r\n");
      out.write("\t\thighData,\r\n");
      out.write("\t\tlowData,\r\n");
      out.write("\t\tboxData,\r\n");
      out.write("\t\tbarXAxis,\r\n");
      out.write("\t\tHistogramData) {\r\n");
      out.write("\t/*Chart program layouts as found on https://www.chartjs.org/samples/latest/*/\r\n");
      out.write("\t new Chart(\"BellcurveChart\", {\r\n");
      out.write("\t\t  type: 'line',\r\n");
      out.write("\t\t  data: {\r\n");
      out.write("\t\t    labels: xAxsis,\r\n");
      out.write("\t\t    datasets: [{ \r\n");
      out.write("\t\t        data: bellData,\r\n");
      out.write("\t\t        label: document.getElementById(\"divName\").innerHTML,\r\n");
      out.write("\t\t        borderColor: \"#3e95cd\",\r\n");
      out.write("\t\t        fill: false\r\n");
      out.write("\t\t      }]\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  options: {\r\n");
      out.write("\t\t    title: {\r\n");
      out.write("\t\t      display: true,\r\n");
      out.write("\t\t      text: 'Bell Curve Graph'\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t \r\n");
      out.write("\t new Chart(\"HighLineGraph\", {\r\n");
      out.write("\t\t  type: 'line',\r\n");
      out.write("\t\t  data: {\r\n");
      out.write("\t\t    labels: xAxsis,\r\n");
      out.write("\t\t    datasets: [{ \r\n");
      out.write("\t\t        data: highData,\r\n");
      out.write("\t\t        label: document.getElementById(\"divName\").innerHTML,\r\n");
      out.write("\t\t        borderColor: \"#3e95cd\",\r\n");
      out.write("\t\t        fill: false\r\n");
      out.write("\t\t      }]\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  options: {\r\n");
      out.write("\t\t    title: {\r\n");
      out.write("\t\t      display: true,\r\n");
      out.write("\t\t      text: 'Data Graph from high to low'\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t \r\n");
      out.write("\t new Chart(\"LowLineGraph\", {\r\n");
      out.write("\t\t  type: 'line',\r\n");
      out.write("\t\t  data: {\r\n");
      out.write("\t\t    labels: xAxsis,\r\n");
      out.write("\t\t    datasets: [{ \r\n");
      out.write("\t\t        data: lowData,\r\n");
      out.write("\t\t        label: document.getElementById(\"divName\").innerHTML,\r\n");
      out.write("\t\t        borderColor: \"#3e95cd\",\r\n");
      out.write("\t\t        fill: false\r\n");
      out.write("\t\t      }]\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  options: {\r\n");
      out.write("\t\t    title: {\r\n");
      out.write("\t\t      display: true,\r\n");
      out.write("\t\t      text: 'Data Graph from low to high'\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t \r\n");
      out.write("\t new Chart(\"HistogramChart\", {\r\n");
      out.write("\t\t  type: 'bar',\r\n");
      out.write("\t\t  data: {\r\n");
      out.write("\t\t    labels: barXAxis,\r\n");
      out.write("\t\t    datasets: [{ \r\n");
      out.write("\t\t        data: HistogramData,\r\n");
      out.write("\t\t        label: document.getElementById(\"divName\").innerHTML,\r\n");
      out.write("\t\t        borderColor: \"#3e95cd\",\r\n");
      out.write("\t\t        fill: false\r\n");
      out.write("\t\t      }]\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  options: {\r\n");
      out.write("\t\t    title: {\r\n");
      out.write("\t\t      display: true,\r\n");
      out.write("\t\t      text: 'Histogram Chart'\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t \r\n");
      out.write("\t var chart = new CanvasJS.Chart(\"BoxandWhisker\", {\r\n");
      out.write("\t\t\ttitle:{\r\n");
      out.write("\t\t\t\ttext: \"Box And Whisker Plot\"\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\taxisY: {\r\n");
      out.write("\t\t\t\tinterval: 40\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdata: [{\r\n");
      out.write("\t\t\t\ttype: \"boxAndWhisker\",\r\n");
      out.write("\t\t\t\tupperBoxColor: \"#FFC28D\",\r\n");
      out.write("\t\t\t\tlowerBoxColor: \"#9ECCB8\",\r\n");
      out.write("\t\t\t\tcolor: \"black\",\r\n");
      out.write("\t\t\t\tdataPoints: [\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t{ label: document.getElementById(\"divName\").innerHTML, y: boxData }\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t\t}]\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tchart.render();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function renderChart(input) {\r\n");
      out.write("\t/*Chart program layouts as found on https://www.chartjs.org/samples/latest/*/\r\n");
      out.write("\tdocument.getElementById('display2').innerHTML=input;\r\n");
      out.write("\t  var chart = new Chart(\"chartContainer\", { \r\n");
      out.write("\t\t  type: 'line',\r\n");
      out.write("\t\t\t  data: {\r\n");
      out.write("\t\t\t    labels: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],\r\n");
      out.write("\t\t\t    datasets: [{ \r\n");
      out.write("\t\t\t        data: input,\r\n");
      out.write("\t\t\t        label: 'My first dataset',\r\n");
      out.write("\t\t\t        borderColor: \"#3e95cd\",\r\n");
      out.write("\t\t\t        fill: false\r\n");
      out.write("\t\t\t     }]\r\n");
      out.write("\t\t\t  },\r\n");
      out.write("\t\t\t  options: {\r\n");
      out.write("\t\t\t    title: {\r\n");
      out.write("\t\t\t      display: true,\r\n");
      out.write("\t\t\t      text: 'Simple Line Chart'\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t  chart.render();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- A stylish Header that contains all futuer user options -->\r\n");
      out.write("    <div class=\"headder\">\r\n");
      out.write("  <div style=\"text-align:left;float:left;\">\r\n");
      out.write("  <h2>JBA Shipping Inc.</h2>\r\n");
      out.write("  <p class=\"c\" >We Deliver the Best to Deliver You Success</p>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Call server for User information -->\r\n");
      out.write("  ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <hr style=\"background-color:white;\"/>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"printResult\">\r\n");
      out.write("<p>The Results of your selected operations:</p>\r\n");
      out.write("<!-- Display The result of the users choices -->\r\n");
      out.write("<textarea id=\"CreatedObject\" rows=\"12\" cols=\"150\" readonly>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\r\n");
      out.write("<p id=\"UserChoice1\">Would you like to crate another object or close the curent working file</p>\r\n");
      out.write("<!-- A list of array choices to analyze -->\r\n");
      out.write(" <div id=\"sizecontroll\">\r\n");
      out.write(" <select name=\"category\"  style=\"float:left;\" class=\"form-control\" onChange=\"window.location.href=this.value\">\r\n");
      out.write("    <option value=\"none\">Choose A region</option>\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write(" <!-- button to launch the Save and quit button options modal  -->\r\n");
      out.write("<div id=\"modal-isi-body\"></div>\r\n");
      out.write("<button  style=\"float:right;\" class=\"btn btn-primary\" id=\"LoadFile\" onclick=\"getModal()\">Close file</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("\t<hr style=\"background-color:black;\"/>\r\n");
      out.write("\tCopyright &copy; 2020. All rights reserved\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/Analitics/Display_Record.jsp(29,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        <form id=\"logoutForm\" method=\"POST\" action=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logout\">\r\n");
          out.write("            <input type=\"hidden\" name=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\r\n");
          out.write("        </form>\r\n");
          out.write("        <h2 style=\"text-align:right; float:right;\">Welcome ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" | <a onclick=\"document.forms['logoutForm'].submit()\">Logout</a></h2>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/Analitics/Display_Record.jsp(48,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/Analitics/Display_Record.jsp(48,4) '${listCategory}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listCategory}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/Analitics/Display_Record.jsp(48,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("category");
      // /WEB-INF/jsp/Analitics/Display_Record.jsp(48,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    \t");
            if (_jspx_meth_spring_005furl_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("        <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${DataSelectURL }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f0 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f0_reused = false;
    try {
      _jspx_th_spring_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/jsp/Analitics/Display_Record.jsp(49,5) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/Stats/chosenewdata/${loop.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/jsp/Analitics/Display_Record.jsp(49,5) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setVar("DataSelectURL");
      int[] _jspx_push_body_count_spring_005furl_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f0 = _jspx_th_spring_005furl_005f0.doStartTag();
        if (_jspx_th_spring_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f0);
      _jspx_th_spring_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f0_reused);
    }
    return false;
  }
}
